### ISSUE TITLE
Using AICP on this device creates a lot of files to not be found

### ISSUE THREAD

**Issue by CurveOS** [Myself5/android_device_sony_maple#1]
I noticed how a lot of proprietary files won't get extracted from this device if use AICP even though it's based on AOSP.

Is there a way to adapt the extract script to work on other roms as well?

**Comment by CurveOS** [comment]
Here's the full output on running ./extract-files.sh: https://hastebin.com/raw/arigobazaq

**Comment by CurveOS** [comment]
What can be done? It sure isn't easy to build AOSP for this device even though I follow the instructions on the sonyxperiadev's page on how to build Oreo.

**Comment by Myself5** [comment]
These devicetrees have nothing to do with the Sony Open Development Project. They are WIP and highly experimental. 

You need to pull these files from Stock. Other ROMs are all using sonyxperiadevs trees. They don't use stock binaries.

For now, I'd recommend to stay away from these trees as I'm still working on fixes and potential forcepushes will mess up your workflow.

To be perfectly clear again: they are at no point related to the Sony Open Device Project nor use any source/blobs from them. They are purely based on Sonys stock sources and binaries as well as @cryptomilks work.
